title: "Riz AI Blog"
date: 2019-04-25

title: "Riz AI Blog"
author: Riz
email: Riz@riz.com
description: > # this means to ignore newlines until "baseurl:"
  Watch the space, coming to a virtual place near you

# social links
twitter_username: Riz@twitter-handle
github_username:  Riz@github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
