title: Riz Architect
author: Riz User
email: riz@riz.com
description: > # this means to ignore newlines until "baseurl:"
  This is how we do it here on the west side of eastern province

# social links
twitter_username: riz@witter-handle
github_username:  riz@github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
